name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pytest --cov=dmp --cov-report=html --cov-report=xml:reports/coverage.xml
        mv htmlcov reports/

    - name: Run mutation tests
      run: mutmut run --paths-to-mutate dmp.py --runner "pytest -x"

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: reports

    - name: Check code formatting
      run: |
        black --check .
        flake8 .
        
    - name: Run regression tests
      run: |
        pytest tests/test_regression.py -v --cov-append